
files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 2
    - max-depth: 2
  border-zero: 2
  brace-style: 2
  class-name-format: 0
  clean-import-paths:
    - 2
    - filename-extension: false
  leading-underscore: false
  empty-args: 0
  empty-line-between-blocks: 2
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    - convention: hyphenatedlowercase
  hex-length:
    - 2
    - style: short
  hex-notation:
    - 2
    - style: uppercase
  id-name-format: 2
  indentation:
    - 2
    - size: 4
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - convention: hyphenatedlowercase
  mixins-before-declarations: 2
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keyword: 0
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    - exclude:
      - src
      - white-space
      - -webkit-tap-highlight-color
  no-empty-rulesets: 2
  no-ids: 1
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties:
      - align-item
      - focus-ring-color
      - osx-font-smoothing
      - overflow-scrolling
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
  allow-element-with-class: false
  allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 1
  no-url-protocols: 2
  no-vendor-prefixes: 0
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format: 0
  property-sort-order: 2
  property-units: 2
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 1
  space-after-bang:
    - 2
    - include: false
  space-after-colon:
    - 2
    - include: true
  space-after-comma: 2
  space-around-operator: 0
  space-before-bang:
    - 2
    - include: true
  space-before-brace:
  - 2
  - include: true
  space-before-colon: 2
  space-between-parens:
    - 2
    - include: false
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 2
  variable-name-format:
    - 2
    - convention: hyphenatedlowercase
  zero-unit: 1
